config/routes.rb
SampleApp::Application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions,  only: [:create, :destroy]
  root  'paginas_estaticas#home'
  match '/ingresar',    to: 'sesiones#new',               via: 'get'
  match '/salir',       to: 'sesiones#destroy',           via: 'delete'
  match '/ayuda',       to: 'paginas_estaticas#help',     via: 'get'
  match '/inscribirse', to: 'usuarios#new',               via: 'get'
  match '/acercade',    to: 'paginas_estaticas#about',    via: 'get'
  match '/contacto',    to: 'paginas_estaticas#contacto', via: 'get'

end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.usuario), feed_item.usuario %>
  <span class="usuario">
    <%= link_to feed_item.usuario.nombre, feed_item.usuario %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posteado hace <%= time_ago_in_words(feed_item.created_at) %>.
  </span>
  <% if usuario_actual?(feed_item.usuario) %>
    <%= link_to "borrar", feed_item, method: :delete,
                                     data: { confirm: "¿Estas seguro?" },
                                     title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_formulario_micropost.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/mensajes_error', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Crea un nuevo micropost..." %>
  </div>
  <%= f.submit "Postear", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_mensajes_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      El formulario contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @usuario ||= usuario_actual %>
<div class="stats">
  <a href="<%= siguiendo_usuario_path(@usuario) %>">
    <strong id="siguiendo" class="stat">
      <%= @usuario.usuarios_seguidos.count %>
    </strong>
    siguiendo
  </a>
  <a href="<%= seguidores_usuario_path(@usuario) %>">
    <strong id="seguidores" class="stat">
      <%= @usuario.seguidores.count %>
    </strong>
    seguidores
  </a>
</div>

app/views/shared/_usuario_info.html.erb
<%= link_to gravatar_for(usuario_actual, size: 52), usuario_actual %>
<h1>
  <%= usuario_actual.nombre %>
</h1>
<span>
  <%= link_to "ver mi perfil", usuario_actual %>
</span>
<span>
  <%= pluralize(usuario_actual.microposts.count, "micropost") %>
</span>