config/routes.rb
SampleApp::Application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions,  only: [:create, :destroy]
  root  'paginas_estaticas#home'
  match '/ingresar',    to: 'sesiones#new',               via: 'get'
  match '/salir',       to: 'sesiones#destroy',           via: 'delete'
  match '/ayuda',       to: 'paginas_estaticas#help',     via: 'get'
  match '/inscribirse', to: 'usuarios#new',               via: 'get'
  match '/acercade',    to: 'paginas_estaticas#about',    via: 'get'
  match '/contacto',    to: 'paginas_estaticas#contacto', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Tutorial Rails</a>
    por Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "Acerca de", acercade_path %></li>
      <li><%= link_to "Contacto", contacto_path %></li>
      <li><a href="http://news.railstutorial.org/">Noticias</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Ayuda",   ayuda_path %></li>
          <% if ingresar? %>
            <li><%= link_to "Usuarios", usuarios_path %></li>
            <li id="fat_menu" class="dropdown">
              <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                Cuenta <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil", usuario_actual %></li>
                <li><%= link_to "Configuración", edit_usuario_path(usuario_actual) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Salir", salir_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Ingresar", ingresar_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |clave, valor| %>
      <div class="alert alert-<%= clave %>"><%= valor %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>