config/routes.rb
SampleApp::Application.routes.draw do
  resources :usuarios do
    member do
      get :siguiendo, :seguidores
    end
  end
  resources :sesiones,   only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relacions,  only: [:create, :destroy]
  root  'paginas_estaticas#home'
  match '/ingresar',    to: 'sesiones#new',               via: 'get'
  match '/salir',       to: 'sesiones#destroy',           via: 'delete'
  match '/ayuda',       to: 'paginas_estaticas#help',     via: 'get'
  match '/inscribirse', to: 'usuarios#new',               via: 'get'
  match '/acercade',    to: 'paginas_estaticas#about',    via: 'get'
  match '/contacto',    to: 'paginas_estaticas#contacto', via: 'get'

end

app/controllers/paginas_estaticas_controller.rb
class PaginasEstaticasController < ApplicationController
  def home
    if ingresar?
      @micropost = usuario_actual.microposts.build
      @feed_items = usuario_actual.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contacto
  end
end

app/helpers/paginas_estaticas_helper.rb
module PaginasEstaticasHelper
end

app/views/paginas_estaticas/about.html.erb
<% provide(:title, 'Acerca de Nosotros') %>
<h1>Acerca de Nosotros</h1>
<p>
  El <a href="http://railstutorial.org/">Tutorial Ruby on Rails</a>
  es un proyecto para hacer un libro y screencasts para enzeñar desarrollo web
  con <a href="http://rubyonrails.org/">Ruby on Rails</a>. Esta es una
  aplicación de muestra para el tutorial.
</p>

app/views/paginas_estaticas/contacto.html.erb
<% provide(:title, 'Contacto') %>
<h1>Contacto</h1>
<p>
  Contacto Tutorial Ruby on Rails sobre la aplicación de muestra en la
  <a href="http://railstutorial.org/contact">página de contacto</a>.
</p>

app/views/paginas_estaticas/help.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
<p>
  Obtiene ayuda sobre el Tutorial Ruby on Rails en la
  <a href="http://railstutorial.org/help">página de ayuda del Tutorial Rails</a>.
  Para obtener ayuda sobre esta aplicación de ejemplo, revisa el
  <a href="http://railstutorial.org/book">libro Tutorial Rails</a>.
</p>

app/views/paginas_estaticas/home.html.erb
<% if ingresar? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/usuario_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/formulario_micropost' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Bienvenidos a Sample App</h1>
    <h2>
      Este es el home page para la aplicación ejemplo del
      <a href="http://railstutorial.org/">Tutorial Ruby on Rails</a>.
    </h2>

    <%= link_to "Inscribete ahora!", inscribirse_path, class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>
<% end %>